# Do I need to do an if __main__ here?
# I didnt copy codecshortname into a dict it is nigh the same as codec altname

from collections import defaultdict
from ts_attrconst import StreamType, AudioMode

isolangdict = defaultdict(lambda: str("Unknown"), {
"abk": "Abkhazian",
"ace": "Achinese",
"ach": "Acoli",
"ada": "Adangme",
"aar": "Afar",
"afh": "Afrihili",
"afr": "Afrikaans",
"afa": "Afro-Asiatic (Other)",
"aka": "Akan",
"akk": "Akkadian",
"alb": "Albanian",
"sqi": "Albanian",
"ale": "Aleut",
"alg": "Algonquian languages",
"tut": "Altaic (Other)",
"amh": "Amharic",
"apa": "Apache languages",
"ara": "Arabic",
"arc": "Aramaic",
"arp": "Arapaho",
"arn": "Araucanian",
"arw": "Arawak",
"arm": "Armenian",
"hye": "Armenian",
"art": "Artificial (Other)",
"asm": "Assamese",
"ath": "Athapascan languages",
"aus": "Australian languages",
"map": "Austronesian (Other)",
"ava": "Avaric",
"ave": "Avestan",
"awa": "Awadhi",
"aym": "Aymara",
"aze": "Azerbaijani",
"ban": "Balinese",
"bat": "Baltic (Other)",
"bal": "Baluchi",
"bam": "Bambara",
"bai": "Bamileke languages",
"bad": "Banda",
"bnt": "Bantu (Other)",
"bas": "Basa",
"bak": "Bashkir",
"baq": "Basque",
"eus": "Basque",
"btk": "Batak (Indonesia)",
"bej": "Beja",
"bel": "Belarusian",
"bem": "Bemba",
"ben": "Bengali",
"ber": "Berber (Other)",
"bho": "Bhojpuri",
"bih": "Bihari",
"bik": "Bikol",
"bin": "Bini",
"bis": "Bislama",
"bos": "Bosnian",
"bra": "Braj",
"bre": "Breton",
"bug": "Buginese",
"bul": "Bulgarian",
"bua": "Buriat",
"bur": "Burmese",
"mya": "Burmese",
"cad": "Caddo",
"car": "Carib",
"cat": "Catalan",
"cau": "Caucasian (Other)",
"ceb": "Cebuano",
"cel": "Celtic (Other)",
"cai": "Central American Indian (Other)",
"chg": "Chagatai",
"cmc": "Chamic languages",
"cha": "Chamorro",
"che": "Chechen",
"chr": "Cherokee",
"chy": "Cheyenne",
"chb": "Chibcha",
"chi": "Chinese",
"zho": "Chinese",
"chn": "Chinook jargon",
"chp": "Chipewyan",
"cho": "Choctaw",
"chu": "Church Slavic",
"chk": "Chuukese",
"chv": "Chuvash",
"cop": "Coptic",
"cor": "Cornish",
"cos": "Corsican",
"cre": "Cree",
"mus": "Creek",
"crp": "Creoles and pidgins (Other)",
"cpe": "Creoles and pidgins,",
"cpf": "Creoles and pidgins,",
"cpp": "Creoles and pidgins,",
"scr": "Croatian",
"hrv": "Croatian",
"cus": "Cushitic (Other)",
"cze": "Czech",
"ces": "Czech",
"dak": "Dakota",
"dan": "Danish",
"day": "Dayak",
"del": "Delaware",
"din": "Dinka",
"div": "Divehi",
"doi": "Dogri",
"dgr": "Dogrib",
"dra": "Dravidian (Other)",
"dua": "Duala",
"dut": "Dutch",
"nld": "Dutch",
"dum": "Dutch, Middle (ca. 1050-1350)",
"dyu": "Dyula",
"dzo": "Dzongkha",
"efi": "Efik",
"egy": "Egyptian (Ancient)",
"eka": "Ekajuk",
"elx": "Elamite",
"eng": "English",
"enm": "English, Middle (1100-1500)",
"ang": "English, Old (ca.450-1100)",
"epo": "Esperanto",
"est": "Estonian",
"ewe": "Ewe",
"ewo": "Ewondo",
"fan": "Fang",
"fat": "Fanti",
"fao": "Faroese",
"fij": "Fijian",
"fin": "Finnish",
"fiu": "Finno-Ugrian (Other)",
"fon": "Fon",
"fre": "French",
"fra": "French",
"frm": "French, Middle (ca.1400-1600)",
"fro": "French, Old (842-ca.1400)",
"fry": "Frisian",
"fur": "Friulian",
"ful": "Fulah",
"gaa": "Ga",
"glg": "Gallegan",
"lug": "Ganda",
"gay": "Gayo",
"gba": "Gbaya",
"gez": "Geez",
"geo": "Georgian",
"kat": "Georgian",
"ger": "German",
"deu": "German",
"nds": "Saxon",
"gmh": "German, Middle High (ca.1050-1500)",
"goh": "German, Old High (ca.750-1050)",
"gem": "Germanic (Other)",
"gil": "Gilbertese",
"gon": "Gondi",
"gor": "Gorontalo",
"got": "Gothic",
"grb": "Grebo",
"grc": "Greek, Ancient (to 1453)",
"gre": "Greek",
"ell": "Greek",
"grn": "Guarani",
"guj": "Gujarati",
"gwi": "Gwich´in",
"hai": "Haida",
"hau": "Hausa",
"haw": "Hawaiian",
"heb": "Hebrew",
"her": "Herero",
"hil": "Hiligaynon",
"him": "Himachali",
"hin": "Hindi",
"hmo": "Hiri Motu",
"hit": "Hittite",
"hmn": "Hmong",
"hun": "Hungarian",
"hup": "Hupa",
"iba": "Iban",
"ice": "Icelandic",
"isl": "Icelandic",
"ibo": "Igbo",
"ijo": "Ijo",
"ilo": "Iloko",
"inc": "Indic (Other)",
"ine": "Indo-European (Other)",
"ind": "Indonesian",
"ina": "Interlingua (International",
"ile": "Interlingue",
"iku": "Inuktitut",
"ipk": "Inupiaq",
"ira": "Iranian (Other)",
"gle": "Irish",
"mga": "Irish, Middle (900-1200)",
"sga": "Irish, Old (to 900)",
"iro": "Iroquoian languages",
"ita": "Italian",
"jpn": "Japanese",
"jav": "Javanese",
"jrb": "Judeo-Arabic",
"jpr": "Judeo-Persian",
"kab": "Kabyle",
"kac": "Kachin",
"kal": "Kalaallisut",
"kam": "Kamba",
"kan": "Kannada",
"kau": "Kanuri",
"kaa": "Kara-Kalpak",
"kar": "Karen",
"kas": "Kashmiri",
"kaw": "Kawi",
"kaz": "Kazakh",
"kha": "Khasi",
"khm": "Khmer",
"khi": "Khoisan (Other)",
"kho": "Khotanese",
"kik": "Kikuyu",
"kmb": "Kimbundu",
"kin": "Kinyarwanda",
"kir": "Kirghiz",
"kom": "Komi",
"kon": "Kongo",
"kok": "Konkani",
"kor": "Korean",
"kos": "Kosraean",
"kpe": "Kpelle",
"kro": "Kru",
"kua": "Kuanyama",
"kum": "Kumyk",
"kur": "Kurdish",
"kru": "Kurukh",
"kut": "Kutenai",
"lad": "Ladino",
"lah": "Lahnda",
"lam": "Lamba",
"lao": "Lao",
"lat": "Latin",
"lav": "Latvian",
"ltz": "Letzeburgesch",
"lez": "Lezghian",
"lin": "Lingala",
"lit": "Lithuanian",
"loz": "Lozi",
"lub": "Luba-Katanga",
"lua": "Luba-Lulua",
"lui": "Luiseno",
"lun": "Lunda",
"luo": "Luo (Kenya and Tanzania)",
"lus": "Lushai",
"mac": "Macedonian",
"mkd": "Macedonian",
"mad": "Madurese",
"mag": "Magahi",
"mai": "Maithili",
"mak": "Makasar",
"mlg": "Malagasy",
"may": "Malay",
"msa": "Malay",
"mal": "Malayalam",
"mlt": "Maltese",
"mnc": "Manchu",
"mdr": "Mandar",
"man": "Mandingo",
"mni": "Manipuri",
"mno": "Manobo languages",
"glv": "Manx",
"mao": "Maori",
"mri": "Maori",
"mar": "Marathi",
"chm": "Mari",
"mah": "Marshall",
"mwr": "Marwari",
"mas": "Masai",
"myn": "Mayan languages",
"men": "Mende",
"mic": "Micmac",
"min": "Minangkabau",
"mis": "Miscellaneous languages",
"moh": "Mohawk",
"mol": "Moldavian",
"mkh": "Mon-Khmer (Other)",
"lol": "Mongo",
"mon": "Mongolian",
"mos": "Mossi",
"mul": "Multiple languages",
"mun": "Munda languages",
"nah": "Nahuatl",
"nau": "Nauru",
"nav": "Navajo",
"nde": "Ndebele, North",
"nbl": "Ndebele, South",
"ndo": "Ndonga",
"nep": "Nepali",
"new": "Newari",
"nia": "Nias",
"nic": "Niger-Kordofanian (Other)",
"ssa": "Nilo-Saharan (Other)",
"niu": "Niuean",
"non": "Norse, Old",
"nai": "North American Indian (Other)",
"sme": "Northern Sami",
"nor": "Norwegian",
"nob": "Norwegian Bokmål",
"nno": "Norwegian Nynorsk",
"nub": "Nubian languages",
"nym": "Nyamwezi",
"nya": "Nyanja",
"nyn": "Nyankole",
"nyo": "Nyoro",
"nzi": "Nzima",
"oci": "Occitan",
"oji": "Ojibwa",
"ori": "Oriya",
"orm": "Oromo",
"osa": "Osage",
"oss": "Ossetian",
"oto": "Otomian languages",
"pal": "Pahlavi",
"pau": "Palauan",
"pli": "Pali",
"pam": "Pampanga",
"pag": "Pangasinan",
"pan": "Panjabi",
"pap": "Papiamento",
"paa": "Papuan (Other)",
"per": "Persian",
"fas": "Persian",
"peo": "Persian, Old (ca.600-400 B.C.)",
"phi": "Philippine (Other)",
"phn": "Phoenician",
"pon": "Pohnpeian",
"pol": "Polish",
"por": "Portuguese",
"pra": "Prakrit languages",
"pro": "Provençal",
"pus": "Pushto",
"que": "Quechua",
"roh": "Raeto-Romance",
"raj": "Rajasthani",
"rap": "Rapanui",
"rar": "Rarotongan",
"roa": "Romance (Other)",
"rum": "Romanian",
"ron": "Romanian",
"rom": "Romany",
"run": "Rundi",
"rus": "Russian",
"sal": "Salishan languages",
"sam": "Samaritan Aramaic",
"smi": "Sami languages (Other)",
"smo": "Samoan",
"sad": "Sandawe",
"sag": "Sango",
"san": "Sanskrit",
"sat": "Santali",
"srd": "Sardinian",
"sas": "Sasak",
"sco": "Scots",
"gla": "Gaelic",
"sel": "Selkup",
"sem": "Semitic (Other)",
"scc": "Serbian",
"srp": "Serbian",
"srr": "Serer",
"shn": "Shan",
"sna": "Shona",
"sid": "Sidamo",
"sgn": "Sign languages",
"bla": "Siksika",
"snd": "Sindhi",
"sin": "Sinhalese",
"sit": "Sino-Tibetan (Other)",
"sio": "Siouan languages",
"den": "Slave (Athapascan)",
"sla": "Slavic (Other)",
"slo": "Slovak",
"slk": "Slovak",
"slv": "Slovenian",
"sog": "Sogdian",
"som": "Somali",
"son": "Songhai",
"snk": "Soninke",
"wen": "Sorbian languages",
"nso": "Sotho, Northern",
"sot": "Sotho, Southern",
"sai": "South American Indian (Other)",
"spa": "Spanish",
"suk": "Sukuma",
"sux": "Sumerian",
"sun": "Sundanese",
"sus": "Susu",
"swa": "Swahili",
"ssw": "Swati",
"swe": "Swedish",
"syr": "Syriac",
"tgl": "Tagalog",
"tah": "Tahitian",
"tai": "Tai (Other)",
"tgk": "Tajik",
"tmh": "Tamashek",
"tam": "Tamil",
"tat": "Tatar",
"tel": "Telugu",
"ter": "Tereno",
"tet": "Tetum",
"tha": "Thai",
"tib": "Tibetan",
"bod": "Tibetan",
"tig": "Tigre",
"tir": "Tigrinya",
"tem": "Timne",
"tiv": "Tiv",
"tli": "Tlingit",
"tpi": "Tok Pisin",
"tkl": "Tokelau",
"tog": "Tonga (Nyasa)",
"ton": "Tonga (Tonga Islands)",
"tsi": "Tsimshian",
"tso": "Tsonga",
"tsn": "Tswana",
"tum": "Tumbuka",
"tur": "Turkish",
"ota": "Turkish, Ottoman (1500-1928)",
"tuk": "Turkmen",
"tvl": "Tuvalu",
"tyv": "Tuvinian",
"twi": "Twi",
"uga": "Ugaritic",
"uig": "Uighur",
"ukr": "Ukrainian",
"umb": "Umbundu",
"und": "Unknown",
"urd": "Urdu",
"uzb": "Uzbek",
"vai": "Vai",
"ven": "Venda",
"vie": "Vietnamese",
"vol": "Volapük",
"vot": "Votic",
"wak": "Wakashan languages",
"wal": "Walamo",
"war": "Waray",
"was": "Washo",
"wel": "Welsh",
"cym": "Welsh",
"wol": "Wolof",
"xho": "Xhosa",
"sah": "Yakut",
"yao": "Yao",
"yap": "Yapese",
"yid": "Yiddish",
"yor": "Yoruba",
"ypk": "Yupik languages",
"znd": "Zande",
"zap": "Zapotec",
"zen": "Zenaga",
"zha": "Zhuang",
"zul": "Zulu",
"zun": "Zuni"
})

# For this dictionary unlike the original I had to move the DTS_Audio values and AC3 Audio values to an external function with a kicker value below because of need to determine Extended Audio Modes of those types
codecnamedict = defaultdict(lambda: str("Unknown"), {
StreamType.MPEG1_VIDEO: "MPEG-1 Video",
StreamType.MPEG2_VIDEO:  "MPEG-2 Video",
StreamType.AVC_VIDEO:  "MPEG-4 AVC Video",
StreamType.MVC_VIDEO:  "MPEG-4 MVC Video",
StreamType.VC1_VIDEO:  "VC-1 Video",
StreamType.MPEG1_AUDIO:  "MP1 Audio",
StreamType.MPEG2_AUDIO:  "MP2 Audio",
StreamType.LPCM_AUDIO:  "LPCM Audio",
StreamType.AC3_PLUS_AUDIO: "Dolby Digital Plus Audio",
StreamType.AC3_PLUS_SECONDARY_AUDIO:  "Dolby Digital Plus Audio",
StreamType.AC3_TRUE_HD_AUDIO:  "Dolby TrueHD Audio",
StreamType.DTS_HD_AUDIO:  "DTS-HD High-Res Audio",
StreamType.DTS_HD_SECONDARY_AUDIO:  "DTS Express",
StreamType.DTS_HD_MASTER_AUDIO:  "DTS-HD Master Audio",
StreamType.PRESENTATION_GRAPHICS:  "Presentation Graphics",
StreamType.INTERACTIVE_GRAPHICS:  "Interactive Graphics",
StreamType.SUBTITLE:  "Subtitle",
})


altcodecdict = defaultdict(lambda: str("Unknown"), {
StreamType.MPEG1_VIDEO:  "MPEG-1",
StreamType.MPEG2_VIDEO:  "MPEG-2",
StreamType.AVC_VIDEO:  "AVC",
StreamType.MVC_VIDEO:  "MVC",
StreamType.VC1_VIDEO:  "VC-1",
StreamType.MPEG1_AUDIO:  "MP1",
StreamType.MPEG2_AUDIO:  "MP2",
StreamType.LPCM_AUDIO:  "LPCM",
StreamType.AC3_AUDIO:  "DD AC3",
StreamType.AC3_PLUS_AUDIO: "DD AC3+",
StreamType.AC3_PLUS_SECONDARY_AUDIO: "DD AC3+",
StreamType.AC3_TRUE_HD_AUDIO:  "Dolby TrueHD",
StreamType.DTS_AUDIO:  "DTS",
StreamType.DTS_HD_AUDIO:  "DTS-HD Hi-Res",
StreamType.DTS_HD_SECONDARY_AUDIO:  "DTS Express",
StreamType.DTS_HD_MASTER_AUDIO:  "DTS-HD Master",
StreamType.PRESENTATION_GRAPHICS:  "PGS",
StreamType.INTERACTIVE_GRAPHICS:  "IGS",
StreamType.SUBTITLE:  "SUB",
 })

# The kicker should be the objects value optionally passed to determine if it is Extended Audio Mode from the AC3 or DTS formats above
def codecnamefunc(threecode, kicker=666):
    if threecode == StreamType.AC3_AUDIO:
        if kicker == AudioMode.Extended:
            return "Dolby Digital EX Audio"
        else:
            return "Dolby Digital Audio"
    elif threecode == StreamType.DTS_AUDIO:
        if kicker == AudioMode.Extended:
              return "DTS ES Audio"
        else:
            return "DTS Audio"
    else:
        return codenamedict[threecode]


def altcodecfunc(threecode):
    return altcodecdict[threecode]


def isolangfunc(threecode):
    return isolangdict[threecode]
